import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import GeneralHeader from "./components/generalHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Providers({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <NextUIProvider>
      {children}
    </NextUIProvider>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <GeneralHeader />
          <>
            {children}
          </>
        </Providers >
      </body>
    </html>

  );
}
